FROM ruby:alpine

# to build gem libraries
RUN apk add make \
            gcc \
            g++ \
            libc-dev \
            libxml2-dev \
            libxslt-dev

ADD ./Gemfile ./
RUN bundle install

# for debugging
RUN apk add bash \
            vim
