FROM ruby:alpine

# change timezone
RUN apk add tzdata \
 && cp /usr/share/zoneinfo/Asia/Seoul /etc/localtime \
 && echo "Asia/Seoul" > /etc/timezone \
 && apk del tzdata

# to build gem libraries
RUN apk add make \
            gcc \
            g++ \
            libc-dev \
            libxml2-dev \
            libxslt-dev

ADD ./Gemfile ./
RUN bundle install

# for debugging
RUN apk add bash \
            vim
